// utils/quizData.js
export const quizQuestions = [
  {
    id: 1,
    question: 'Hvor mye matavfall produserer en gjennomsnittlig norsk familie per år?',
    options: ['10–20 kg', '40–80 kg', '150–200 kg', '300+ kg'],
    correct: 1,
    explanation: 'En gjennomsnittlig norsk familie kaster mellom 40–80 kg mat per år.',
    category: 'matavfall',
  },
  {
    id: 2,
    question: 'Hva er biogass laget av?',
    options: ['Olje og gass', 'Organisk avfall som mat og slam', 'Kull og mineraler', 'Plast og metall'],
    correct: 1,
    explanation: 'Biogass produseres ved nedbryting av organisk materiale som matavfall og kloakkslam.',
    category: 'biogass',
  },
  {
    id: 3,
    question: 'Hvilken klimagass produseres mest fra matavfall på søppelfyllinger?',
    options: ['CO₂', 'Metan (CH₄)', 'Lystgass (N₂O)', 'Ozon (O₃)'],
    correct: 1,
    explanation: 'Metan er 25× kraftigere enn CO₂ som klimagass og produseres i store mengder fra matavfall på søppelfyllinger.',
    category: 'klima',
  },
  {
    id: 4,
    question: 'Omtrent hvor mye CO₂ spares per kg matavfall som omdannes til biogass?',
    options: ['0.1 kg', '0.8 kg', '5 kg', '10 kg'],
    correct: 1,
    explanation: 'Hvert kg matavfall som omdannes til biogass sparer omtrent 0.8 kg CO₂ sammenlignet med deponering.',
    category: 'biogass',
  },
  {
    id: 5,
    question: 'Hva brukes biogass hovedsakelig til?',
    options: ['Å lage plast', 'Varme og elektrisitet', 'Vanning av planter', 'Kjøling'],
    correct: 1,
    explanation: 'Biogass brukes primært til å produsere varme og elektrisitet, og kan også brukes som drivstoff.',
    category: 'biogass',
  },
  {
    id: 6,
    question: 'Hvilken mattype utgjør mest matavfall i norske husholdninger?',
    options: ['Kjøtt', 'Brød og bakevarer', 'Grønnsaker og frukt', 'Meieriprodukter'],
    correct: 2,
    explanation: 'Grønnsaker og frukt utgjør den største andelen av matavfallet i norske hjem.',
    category: 'matavfall',
  },
  {
    id: 7,
    question: 'Hva er det globale målet for reduksjon av matavfall innen 2030?',
    options: ['10% reduksjon', '25% reduksjon', '50% reduksjon', '75% reduksjon'],
    correct: 2,
    explanation: 'FNs bærekraftsmål 12.3 sier at vi skal halvere matavfallet globalt innen 2030.',
    category: 'klima',
  },
  {
    id: 8,
    question: 'Hvor mange prosent av verdens matproduksjon kastes som avfall?',
    options: ['5%', '10%', '33%', '60%'],
    correct: 2,
    explanation: 'Omtrent en tredjedel (33%) av all mat som produseres globalt kastes som avfall.',
    category: 'matavfall',
  },
  {
    id: 9,
    question: 'Hva er den beste måten å redusere matavfall på i hjemmet?',
    options: ['Kjøpe mer mat', 'Planlegge måltidene og lage handleliste', 'Kaste mat raskere', 'Unngå å kjøpe fersk mat'],
    correct: 1,
    explanation: 'Planlegging av måltider og å lage handleliste er den mest effektive måten å redusere matsvinn på.',
    category: 'matavfall',
  },
  {
    id: 10,
    question: 'Hva betyr ordet "bioøkonomi"?',
    options: ['Økonomi basert på olje', 'Økonomi basert på fornybare biologiske ressurser', 'Økonomi basert på metall', 'Økonomi basert på plast'],
    correct: 1,
    explanation: 'Bioøkonomi er en økonomi basert på fornybare biologiske ressurser fra landbogg, skog og hav.',
    category: 'biogass',
  },
  {
    id: 11,
    question: 'Hva er restproduktet etter biogassproduksjon?',
    options: ['Vann', 'Biogjødsel', 'Plast', 'Aske'],
    correct: 1,
    explanation: 'Restproduktet er biogjødsel som er en næringsrik gjødsel for landbruket.',
    category: 'biogass',
  },
  {
    id: 12,
    question: 'Hvor lang tid tar det for matavfall å brytes ned på en søppelfylling?',
    options: ['1 år', '5 år', '20+ år', 'Aldri'],
    correct: 2,
    explanation: 'Matavfall kan ta over 20 år å brytes ned på en fylling, og avgir metan i hele perioden.',
    category: 'klima',
  },
  {
    id: 13,
    question: 'Hva er "matvind"?',
    options: ['Mat som blir vinden blåst bort', 'Mat som kastes før den når forbruker', 'Mat som selges billig', 'Mat som brukes som dyrefôr'],
    correct: 1,
    explanation: 'Matvind er mat som kastes gjennom hele verdikjeden, fra produsent til forbruker.',
    category: 'matavfall',
  },
  {
    id: 14,
    question: 'Kan biogass brukes som drivstoff for biler?',
    options: ['Nei, aldri', 'Ja, i modifiede biler', 'Kun for lastebiler', 'Kun for fly'],
    correct: 1,
    explanation: 'Biogass kan brukes som drivstoff i biler som er tilpasset for det, og brukes allerede av mange busser og lastebiler.',
    category: 'biogass',
  },
  {
    id: 15,
    question: 'Hvor mye energi kan produseres fra 1kg matavfall?',
    options: ['0.5 kWh', '2-3 kWh', '10 kWh', '50 kWh'],
    correct: 1,
    explanation: 'Fra 1 kg matavfall kan det produseres omtrent 2-3 kWh energi som biogass.',
    category: 'biogass',
  },
  {
    id: 16,
    question: 'Hva er "grønn hydrogen"?',
    options: ['Hydrogen fra olje', 'Hydrogen produsert med fornybar energi', 'Hydrogen fra kull', 'Hydrogen fra metall'],
    correct: 1,
    explanation: 'Grønn hydrogen er hydrogen produsert ved elektrolyse med fornybar energi som sol eller vind.',
    category: 'biogass',
  },
  {
    id: 17,
    question: 'Hva er viktigste årsaken til matsvinn i Norge?',
    options: ['Dårlig transport', 'For stor porsjonsstørrelse og dårlig planlegging', 'For dårlig emballasje', 'For høye priser'],
    correct: 1,
    explanation: 'Den viktigste årsaken til matsvinn er for stor porsjonsstørrelse og dårlig planlegging av måltider.',
    category: 'matavfall',
  },
  {
    id: 18,
    question: 'Hvor mye mat kaster hver nordmann i året?',
    options: ['5 kg', '15 kg', '40 kg', '100 kg'],
    correct: 2,
    explanation: 'Hver nordmann kaster i gjennomsnitt omtrent 40 kg mat per år.',
    category: 'matavfall',
  },
  {
    id: 19,
    question: 'Hva er forskjellen mellom nedbrytbart og komposterbart materiale?',
    options: ['Det er ingen forskjell', 'Nedbrytbart brytes ned av seg selv, komposterbart krever spesifikke forhold', 'Komposterbart varer lenger', 'Nedbrytbart er bedre for miljøet'],
    correct: 1,
    explanation: 'Nedbrytbart materiale brytes ned naturlig, mens komposterbart materiale krever spesifikke forhold som temperatur og fuktighet.',
    category: 'klima',
  },
  {
    id: 20,
    question: 'Hva er en sirkulær økonomi?',
    options: ['Økonomi basert på olje', 'Økonomi der ressurser brukes om og om igjen', 'Økonomi basert på import', 'Økonomi basert på avfall'],
    correct: 1,
    explanation: 'Sirkulær økonomi går ut på at ressurser brukes om og om igjen, i motsetning til en lineær økonomi der produkter kastes etter bruk.',
    category: 'biogass',
  },
];

export const categoryColors = {
  matavfall: '#22c55e',
  biogass: '#84cc16',
  klima: '#eab308',
};
